Drop table math_example;



CREATE TABLE math_example
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    example    varchar NOT NULL,
    result     double precision
);
INSERT INTO math_example (example, result) VALUES ('2+2*2', 6);
INSERT INTO math_example (example, result) VALUES ('(2+2)*2', 8);



select * from math_example;


select * from math_example where math_example.result < 7;






